version: 0.0

os: linux

files:
  - source: basico-0.0.1-SNAPSHOT.jar
    destination: /home/ec2-user/

hooks:
  ApplicationStop:
    - location: scripts/stop-process.sh
      timeout: 180
      runas: root
  ApplicationStart:
    - location: scripts/start-process.sh
      timeout: 180
      runas: root
