version: 0.0

os: linux

files:
  - source: basico-0.0.1-SNAPSHOT.jar
    destination: /home/ec2-user/

hooks:

  ApplicationStart:
    - location: start_process.sh
      timeout: 180
      runas: root
